
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lucas
 */
public class FormPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FormPrincipal
     */
    public FormPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        mnBarPrincipal = new javax.swing.JMenuBar();
        mnCadastro = new javax.swing.JMenu();
        itAbreCadAluno = new javax.swing.JMenuItem();
        itAbreCadExAluno = new javax.swing.JMenuItem();
        itAbreCadServidor = new javax.swing.JMenuItem();
        mnFechar = new javax.swing.JMenu();
        itFechaSistema = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal");

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setText("Sistema de Gestão de Pessoas");

        mnCadastro.setText("Cadastro");

        itAbreCadAluno.setText("Cadastro de Aluno");
        itAbreCadAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itAbreCadAlunoActionPerformed(evt);
            }
        });
        mnCadastro.add(itAbreCadAluno);

        itAbreCadExAluno.setText("Cadastro Ex Aluno");
        itAbreCadExAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itAbreCadExAlunoActionPerformed(evt);
            }
        });
        mnCadastro.add(itAbreCadExAluno);

        itAbreCadServidor.setText("Cadastro Servidor");
        itAbreCadServidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itAbreCadServidorActionPerformed(evt);
            }
        });
        mnCadastro.add(itAbreCadServidor);

        mnBarPrincipal.add(mnCadastro);

        mnFechar.setText("Fechar");

        itFechaSistema.setText("Fechar");
        itFechaSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itFechaSistemaActionPerformed(evt);
            }
        });
        mnFechar.add(itFechaSistema);

        mnBarPrincipal.add(mnFechar);

        setJMenuBar(mnBarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(lblTitulo)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(lblTitulo)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itAbreCadAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itAbreCadAlunoActionPerformed
        FormCadastroA.getFormCadastroA().setVisible(true);
    }//GEN-LAST:event_itAbreCadAlunoActionPerformed

    private void itAbreCadExAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itAbreCadExAlunoActionPerformed
       FormCadastroEx.getFormCadastroEx().setVisible(true);
    }//GEN-LAST:event_itAbreCadExAlunoActionPerformed

    private void itAbreCadServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itAbreCadServidorActionPerformed
        FormCadastroS.getFormCadastroS().setVisible(true);
    }//GEN-LAST:event_itAbreCadServidorActionPerformed

    private void itFechaSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itFechaSistemaActionPerformed
        sair();
    }//GEN-LAST:event_itFechaSistemaActionPerformed

    public void sair(){
        int resp = JOptionPane.showConfirmDialog(null, "Deseja fechar o cadastro??", "Saida", JOptionPane.YES_NO_CANCEL_OPTION);
            if(resp == 0){
                this.dispose();
            }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itAbreCadAluno;
    private javax.swing.JMenuItem itAbreCadExAluno;
    private javax.swing.JMenuItem itAbreCadServidor;
    private javax.swing.JMenuItem itFechaSistema;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JMenuBar mnBarPrincipal;
    private javax.swing.JMenu mnCadastro;
    private javax.swing.JMenu mnFechar;
    // End of variables declaration//GEN-END:variables
}
